<button id="button">
    <span><?= $block->escapeHtml(__('Click me')) ?></span>
</button>

<div id="modal">
    <div class="modal-body-content">
        <h2 data-bind="text: firstname"><?= $block->escapeHtml(__('Title')) ?></h2>
        <p><?= $block->escapeHtml(__('Content   ')) ?></p>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Main title'
        };

        modal(options, $('#modal'));
        $("#button").click(function() {
            $('#modal').modal('openModal');
        });
    });

    function abc() {
        var self = this;
        self.firstname = ko.observable("Hoa");
    }
    ko.applyBinding(new abc(),document.querySelector("#button"))
</script>